version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    restart: always
    volumes_from:
      - app
    ports:
      - 8080:80
    links:
      - app

  # The Database
  database:
    build:
      context: ./
      dockerfile: db.dockerfile
    #image: mysql:5.6
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    #ports:
    #    - "33061:3306"

volumes:
  dbdata:
